[2024-11-12T23:24:54.195+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-12T23:24:54.558+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brew-dag.copy_from_api scheduled__2024-11-11T07:00:00+00:00 [queued]>
[2024-11-12T23:24:54.576+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brew-dag.copy_from_api scheduled__2024-11-11T07:00:00+00:00 [queued]>
[2024-11-12T23:24:54.577+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-12T23:24:54.603+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): copy_from_api> on 2024-11-11 07:00:00+00:00
[2024-11-12T23:24:54.640+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=738) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-12T23:24:54.644+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'brew-dag', 'copy_from_api', 'scheduled__2024-11-11T07:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/brew-dag.py', '--cfg-path', '/tmp/tmp47u6_6ws']
[2024-11-12T23:24:54.651+0000] {standard_task_runner.py:72} INFO - Started process 740 to run task
[2024-11-12T23:24:54.653+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask copy_from_api
[2024-11-12T23:24:54.865+0000] {task_command.py:467} INFO - Running <TaskInstance: brew-dag.copy_from_api scheduled__2024-11-11T07:00:00+00:00 [running]> on host 60459ae802f2
[2024-11-12T23:24:55.023+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brew-dag' AIRFLOW_CTX_TASK_ID='copy_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-11T07:00:00+00:00'
[2024-11-12T23:24:55.029+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-12T23:24:55.029+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-12T23:24:55.030+0000] {logging_mixin.py:190} INFO - Current task name:copy_from_api state:running start_date:2024-11-12 23:24:54.559598+00:00
[2024-11-12T23:24:55.031+0000] {logging_mixin.py:190} INFO - Dag name:brew-dag and current dag run status:running
[2024-11-12T23:24:55.031+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-12T23:25:31.423+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/brew-dag.py", line 49, in copy_from_api
    with open("/Users/nelso/Desktop/CaseDE/datalake/bronze/raw.json", "w") as outfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nelso/Desktop/CaseDE/datalake/bronze/raw.json'
[2024-11-12T23:25:31.448+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-12T23:25:31.449+0000] {logging_mixin.py:190} INFO - Task start:2024-11-12 23:24:54.559598+00:00 end:2024-11-12 23:25:31.446587+00:00 duration:36.886989
[2024-11-12T23:25:31.450+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): copy_from_api> dag:<DAG: brew-dag> dagrun:<DagRun brew-dag @ 2024-11-11 07:00:00+00:00: scheduled__2024-11-11T07:00:00+00:00, state:running, queued_at: 2024-11-12 23:24:14.838184+00:00. externally triggered: False>
[2024-11-12T23:25:31.450+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/Users/nelso/Desktop/CaseDE/datalake/bronze/raw.json'
[2024-11-12T23:25:31.451+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=brew-dag, task_id=copy_from_api, run_id=scheduled__2024-11-11T07:00:00+00:00, execution_date=20241111T070000, start_date=20241112T232454, end_date=20241112T232531
[2024-11-12T23:25:31.487+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-12T23:25:31.488+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task copy_from_api ([Errno 2] No such file or directory: '/Users/nelso/Desktop/CaseDE/datalake/bronze/raw.json'; 740)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/brew-dag.py", line 49, in copy_from_api
    with open("/Users/nelso/Desktop/CaseDE/datalake/bronze/raw.json", "w") as outfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nelso/Desktop/CaseDE/datalake/bronze/raw.json'
[2024-11-12T23:25:31.545+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-12T23:25:31.577+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T23:25:31.584+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
